# Generated by Django 5.0.2 on 2024-04-14 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='Conversation',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
